---
title: "raukR: Day1"
author: "Srinidhi Varadharajan"
date: "6/11/2018"
output: html_document
---

## Coding Best Practices 
https://nbisweden.github.io/RaukR-2018/best_coding_practises_Marcin/presentation/pres_best_coding_practises.html#1

* Double epsilon
    * head(unlist(.Machine))
    * head(unlist(.Platform))

* Profiling
    * profvis and profr

* Copy on modify deafult behavior - memory location check using address() in library(pryr)
* No loops, allocate memory.. 
* parallelize using library(parallel)


```{r setup, include=FALSE}
iterMax <- 5
colNum = 10
rowNum = 10
mat <- matrix(rep(1, colNum*rowNum),nrow=rowNum)

for(i in 1:colNum) {
  for(j in 1:rowNum) {
    if(i >= iterMax){
      mat[i, j]<-NA
    }
  }
}
mat

```


```{r }
simulate_genotype <- function( q, N=100 ) {
  if( length(q) == 1 ){
    p <- (1 - q)
    f_gt <- c(p^2, 2*p*q, q^2) # AA, AB, BB
  }else{
    f_gt<-q
  }
  genotype <- sample( c('AA','AB','BB'),
                      size = N, 
                      prob = f_gt, 
                      replace = T )
  return(genotype)
}
```


```{r , echo=FALSE}
.my_months<- month.abb[10:12]
```

```{r}
my_filter <- function(data,threshold = 1,  scalar = 5) {
  data[data >= threshold] <- NA 
  data <- data * scalar
  return(data)
}
```


```{r}
simulate_phenotype <- function(pop_params, gp_map, gtype) {
  pop_mean <- pop_params[1]
  pop_var <- pop_params[2]
  pheno <- rnorm(n = N, mean = pop_mean, sd = sqrt(pop_var))
  effect <- rep(0, times = length(N))
  for (gt_iter in c('AA', 'AB', 'BB')) {
    effect[gtype == gt_iter] <- rnorm(n = sum(gtype == gt_iter), 
                                      mean = gp_map[gt_iter, 'mean_eff'], 
                                      sd = sqrt(gp_map[gt_iter, 'var_eff']))
  }
  dat <- data.frame(gt = gtype, raw_pheno = pheno, effect = effect, pheno = pheno + effect)
  return(dat)
}
```


```{r}
ariance_calculator<- function(myList){
  #myList<-c(1,2,3,4)
  N <- length(myList)
  myMean<- sum(myList)/N
  Num=0
  for (i in 1:N){
    Num<-Num+(myList[i] - myMean)^2
  }
paste("SD=",sqrt(Num/(N-1)),"\n","variance=",sqrt(Num/(N-1))^2,sep=" ")
}

```

```{r}
randomSampleInt <- function(x, verbose, length, seed = 42) {
  if (verbose) {
    print(paste0('Generating random sample of ', length, ' integers using seed ', seed))
  }
  set.seed(seed)
  sampleInt <- sample(x = x, size = length, replace = TRUE)
  return(sampleInt)
} 


randomSampleLetter <- function(N, silent=T, lett) {
  if (!silent) {
    print(paste0('Generating random sample of ', N, ' letters.'))
  }
  sample <- sample(x = lett, size = N, replace = TRUE)
  return(sample)
}


randomSampleLetter_2<-function(x,verbose,length,seed=42){
  set.seed(seed)
  randomSampleLetter(N=length,silent = !verbose,lett=x)
}
```



```{r}
plotWrapper<- function (data,mycol="red",shape=4,...){
plot(x=data,col=mycol,pch=shape,...)  
}

plot(cars$speed, cars$dist, main = "with(cars, plot(speed, dist))")
plotWrapper(cars$speed, y=cars$dist, main = "with(cars, plot(speed, dist))")
```

```{r}
red_plot <- function(x, y) { 
  plot(x, y, las=1, cex.axis=.8, ...)
}


formals(red_plot)
formals(red_plot)<-alist(x=,y=,... = )
red_plot(1, 1, col='red', pch=19) 


```


```{r}
input <- sample(1:1000, size = 1000, replace = T)
currmin <- 1000
for (i in input) {
  if (i < currmin) {
    currmin <- i
    print(paste0("The new minimum is: ", currmin))
  }
}


input <- sample(1:1000, size = 1000, replac = T)
currmin <- NULL
for (i in input) {
  if (input < currmin) {
    currmin <- input
    print(paste0("The new minimum is: ", currmin))
  }
}

for (cnt in 1:100) {
  if (cnt > 12) {
    print("12+")
  } else {
    print("Not 12+")
  }
}

```

```{r}
result <- logical(10)
input <- sample(1:10, size = 10, replace = T)
for (i in 1:length(input)) {
  if (input[i] >= 5) {
    result[i] <- TRUE
  }
}
print(i)
```

```{r}
vec <- seq(0.1, 0.9, by=0.1)
vec == 0.7

ActuallyEqual<-

```

```{r}

t1<-proc.time()
x<-matrix(data = sample(x = 1:42,size = 10000*10000,replace = T),ncol = 10000,nrow = 10000,byrow = T)
proc.time() -t1

t2<-proc.time()
x<-matrix(data = sample(x = 1:42,size = 10000*10000,replace = T),ncol = 10000,nrow = 10000,byrow = F)
proc.time() -t2

```


```{r}
plot(unlist(lapply(1:100,function(i) system.time(rnorm(n = 10e6))[[1]])))
plot(replicate(100,system.time(rnorm(n = 10e6))[[1]]),pch=19,col="slateblue")
plot(replicate(100,system.time(rnorm(n = 10e6))[[1]]),pch=19,col="slateblue")
```


```{r}
library(microbenchmark)
microbenchmark::get_nanotime()

timing <- double(100)
for (i in 1:100) {
  st <- system.time(rnorm(n = 10e6))
  timing[i] <- st[3]
}
boxplot(timing)
```


```{r , echo=FALSE}
sessionInfo()
```
